[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

[dependencies]
yew = { version = "0.22.0", features = ["csr"] }
anyhow = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
yew-websocket = { path = "../../"}
